package com.bigsea.mapper;

import com.bigsea.entity.Animal1;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

@Component
@Mapper
public interface Animal1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal1
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal1
     *
     * @mbggenerated
     */
    int insert(Animal1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal1
     *
     * @mbggenerated
     */
    int insertSelective(Animal1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal1
     *
     * @mbggenerated
     */
    Animal1 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal1
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Animal1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal1
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Animal1 record);
}