package com.bigsea.mapper;

import com.bigsea.entity.Animal2;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

@Component
@Mapper
public interface Animal2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal2
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal2
     *
     * @mbggenerated
     */
    int insert(Animal2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal2
     *
     * @mbggenerated
     */
    int insertSelective(Animal2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal2
     *
     * @mbggenerated
     */
    Animal2 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal2
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Animal2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal2
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Animal2 record);
}