package com.bigsea.mapper;

import com.bigsea.entity.BootUser;

public interface BootUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbggenerated
     */
    int insert(BootUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbggenerated
     */
    int insertSelective(BootUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbggenerated
     */
    BootUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BootUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BootUser record);
}